#!/bin/bash
#
# $Id$
#
# Renew Let's Encrypt SSL cert and assemble pem for pound.
#
DOMAINNAME="www.mikeroberts.ca"
NOTIFYEMAIL="postmaster"

LECONFIGDIR="/etc/letsencrypt"
LEINSTALLDIR="/opt/letsencrypt"
LELOG="/opt/letsencrypt"
LECOMMAND="$LEINSTALLDIR/letsencrypt-auto"
LEARGS="--config $LECONFIGDIR/cli.ini -d $DOMAINNAME certonly"

[ -d "$LEINSTALLDIR" ] || exit 1
[ -d "$LECONFIGDIR" ] || exit 1
[ -x "$LECOMMAND" ] || exit 1

COMMAND=`basename $LECOMMAND`
cd $LEINSTALLDIR

echo "executing letsencrypt: $LECOMMAND $LEARGS"
./$COMMAND $LEARGS

if [ $? -ne 0 ]; then
    ERRORLOG=`tail $LELOG`
    echo -e "failure renewing cert. \n \n" $ERRORLOG | mail -s "Lets Encrypt Cert Alert" $NOTIFYEMAIL
else
    echo "success renewing cert."
    # certs are ready so package and restart pound
    cd $LECONFIGDIR/live/$DOMAINNAME
    # package up PEM for webserver and restart 
    cat fullchain.pem privkey.pem > for_pound_ssl.pem
    chmod 400 for_pound_ssl.pem
    echo "for_pound_ssl.pem cert package created."
    service pound restart
    echo "pound restarted."
fi
exit 0
